# Should be one of the malloc implementation available (counter/sentinel/protector/tracker)
CFLAGS=-std=c11 -Wall
MALLOC=counter

OVERRIDEN_FUNCTIONS=-Dmain=alt_main \
					-D__assert_fail=grader_assert_fail \
					-D__assert_perror_fail=grader_assert_perror_fail \
					-Dexit=grader_exit

STUDENT_CODE_CFLAGS=-finstrument-functions -DSTUDENT_MODE
# May be overrided by Makefile.mk
GRADER_ROOT=..

-include Makefile.mk

CFLAGS+=-I$(GRADER_ROOT)/lib -I. -fno-builtin-printf
LDFLAGS+=-lm -ldl -rdynamic

GRADER_FILES=$(GRADER_ROOT)/lib/grader.o $(GRADER_ROOT)/lib/printf.o $(GRADER_ROOT)/lib/malloc-$(MALLOC).o

DEBUG_FLAGS=-ggdb -O0
CFLAGS_EXO+=$(GRADER_FLAGS) \
						-Wno-error=address -Wno-error=format -Wno-error=missing-field-initializers \
						-Wno-address -Wno-format -Wno-missing-field-initializers
GRADER_FLAGS=-Wno-error

ifndef ILLEGAL
ILLEGAL=assert_passed
endif

ILLEGAL_PAT=($(strip $(ILLEGAL))|_exit|assert_passed|reset_user_assert)

%: %.c libexam.a
		(\
			echo '#line 1 "prolog.c"' ; \
			ar p libexam.a prolog.c 2>/dev/null ;\
			echo '#line 1 "$(notdir $<)"' ; \
			cat $<  ;\
			echo ';' ; \
			echo '#line 1 "epilog.c"' ; \
			ar p libexam.a epilog.c 2>/dev/null \
		) | $(CC) -xc $(CFLAGS) -c -o $@.o $(DEBUG_FLAGS) $(OVERRIDEN_FUNCTIONS) $(STUDENT_CODE_CFLAGS) -
		nm -u $@.o 2>/dev/null | egrep -q "[Uu] \b$(ILLEGAL_PAT)\b" && echo "Veuillez ne pas utiliser, appeller ou créer, de fonction dont le nom est :" `nm $@.o 2>/dev/null | egrep -o "\b$(ILLEGAL_PAT)\b"` && exit 1 || true
	$(CC) -o $@ $@.o libexam.a $(LDFLAGS)
$(GRADER_ROOT)/lib/grader.o: $(GRADER_ROOT)/lib/grader.c $(GRADER_ROOT)/lib/grader2.h
	$(CC) -c -o $@ $(DEBUG_FLAGS) $(CFLAGS) $(GRADER_FLAGS) $<
exercice.o: exercice.c $(DEPS)
	$(CC) -c -o $@ $(DEBUG_FLAGS) $(CFLAGS_EXO) $(CFLAGS) $<
libexam.a:
	$(AR) $(ARFLAGS) -c $@ $^ > /dev/null
enonce.c: provided.c
	$(GRADER_ROOT)/lib/extract_subject $< > $@
provided.h: provided.c
	$(GRADER_ROOT)/lib/extract_subject --provided $< > $@
provided.o: provided.c
	(\
		echo '#line 1 "prolog.c"' ; \
		cat prolog.c 2>/dev/null ;\
		echo '#line 1 "$(notdir $<)"' ; \
		cat $<  ;\
		echo ';' ; \
		echo '#line 1 "epilog.c"' ; \
		cat epilog.c 2>/dev/null \
	) | $(CC) -xc -c -o $(patsubst %.o,%.tmp.o,$@) $(DEBUG_FLAGS) $(CFLAGS_EXO) $(CFLAGS) -
	$(GRADER_ROOT)/lib/redefine_syms $(patsubst %.o,%.tmp.o,$@) $@
clean:
	$(RM) $(GRADER) $(DEPS)
